# Dockerfile used for development and testing
FROM python:latest AS base

RUN apt-get update --allow-releaseinfo-change && \
    DEBIAN_FRONTEND="noninteractive" apt-get -yq install \
        bash \
        curl \
        jq \
    && t="/tmp/gh-$$.deb" && curl -sSLo "$t" "https://github.com$(curl -sSL "https://github.com/cli/cli/releases/latest" | grep -Po "(?<=href=\")/cli/cli/releases/download/[^\"]*$(dpkg --print-architecture)[.]deb(?=\")")" && apt-get install -y "$t" && rm "$t" \
    rm -rf /var/lib/apt/lists/* $HOME/.python_history $HOME/.wget-hsts

ENV PYTHONPATH="/"

FROM base AS dev

COPY ./requirements.txt /
RUN pip install -U \
        pip && \
    pip install -r /requirements.txt && \
    rm -rf $HOME/.cache $HOME/.python_history $HOME/.wget-hsts

COPY ./bin/print_issues /docker/print_issues
COPY ./trivy_report /trivy_report
COPY ./tests/ /tests/

RUN chmod +x /docker/*

ENTRYPOINT ["/docker/print_issues"]

FROM dev AS test

ENTRYPOINT []
CMD ["pytest", "/tests"]
